name: Deploy container to Azure Container Apps

on:
  push:
    branches: ["main"]
    paths: ["C_SHARP/API2/**"]
  workflow_dispatch:

permissions:
  contents: read

env:
 # AZURE_FUNCTIONAPP_NAME: 'your-app-name'   # set this to your function app name on Azure
  LOGIN_SERVER: 'nvmacrwatm.azurecr.io'     # set this to login server for your private container registry (e.g. 'contoso.azurecr.io', 'index.docker.io' )
  REGISTRY: 'nvmacrwatm'                    # set this to proper value for REGISTRY
  NAMESPACE: '519F23'                          # set this to proper value for NAMESPACE
  IMAGE: 'queueProcessor'                   # set this to proper value for IMAGE
  TAG: 'foobar'                             # set this to proper value for TAG
  C_NAME: 'nvmacrwatm.azurecr.io/519F23/queueProcessor:foo'
  CONTAINER_APP: 'nvmcontainerapp'
  RESOURCE_GROUP: 'Assignment2'
  
  # LOTS OF CLEANUP NEEDED

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.F23RBAC }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/C_Sharp/API2
        acrName: ${{ env.REGISTRY }}
        containerAppName: ${{ env.CONTAINER_APP }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
      
